Repository blockcoders/near-rpc-providers, pull requests merged in 2021-12, with the labels that each got.

#9 Feature/getLastGasPrice
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/responses.ts
Labels: Feature

#8 Feature/getBlock
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/responses.ts
Labels: Feature

#11 Update readme
  README.md
Labels: documentation

#12 Network unit test
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/networks.spec.ts
  src/networks.ts
Labels: bug, enhancement

#15 Feature/GetCode
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature

#16 Feature/sendTransaction
  package-lock.json
  package.json
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/responses.ts
Labels: Feature

#17 Fix/tests
  package-lock.json
  package.json
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
Labels: bug

#19 Add documentation to README
  README.md
Labels: documentation

#22 Feature/getChunkDetails
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature

#20 Feature/getBlockWithChunk
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature

#24 Feature/getContractState
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature

#26 Feature/getAccessKey
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature

#28 Feature/getAccessKeyList
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature
