Repository blockcoders/near-rpc-providers, pull requests merged in 2022-01, with the labels that each got.

#30 Feature/getNetworkInfo
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/responses.ts
Labels: Feature

#32 Feature/getValidatorStatus
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/responses.ts
Labels: Feature

#34 Feature/Default provider for near rpc
  src/default-provider.ts
  src/near-rpc-provider.spec.ts
Labels: Feature

#37 Feature/call method to invoke a contract
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/responses.ts
Labels: Feature

#39 Feature/Fallback tests
  src/near-rpc-provider.spec.ts
Labels: Feature

#42 Updating the readme file with all new methods
  README.md
Labels: documentation

#43 Sign message and query archival node
  src/near-rpc-provider.spec.ts
  src/near-rpc-provider.ts
  src/parameters.ts
  src/tests/utils.ts
  src/utils.spec.ts
  src/utils.ts
Labels: enhancement
